/* This file is generated by bin_to_c.py script, do not modify. */
#ifndef IOC_SIGNALS_INFO_MBLK_INCLUDED
#define IOC_SIGNALS_INFO_MBLK_INCLUDED
OSAL_C_HEADER_BEGINS

extern OS_PROGMEM_H os_uchar ioapp_signals_config[268];

OSAL_C_HEADER_ENDS
#endif
