/* This file is generated by signals_to_c.py script, do not modify. */
#ifndef IOC_SIGNALS_INCLUDED
#define IOC_SIGNALS_INCLUDED
OSAL_C_HEADER_BEGINS

typedef struct rookie_t
{
  struct 
  {
    iocMblkSignalHdr hdr;
    iocSignal LEFT;
    iocSignal RIGHT;
    iocSignal FORWARD;
    iocSignal BACKWARD;
  }
  exp;

  struct 
  {
    iocMblkSignalHdr hdr;
    iocSignal LeftTurn;
    iocSignal RightTurn;
    iocSignal StraightForward;
    iocSignal ForwardBackward;
  }
  imp;
}
rookie_t;

#define ROOKIE_EXP_MBLK_SZ 24
#define ROOKIE_IMP_MBLK_SZ 24

extern OS_CONST_H rookie_t rookie;
#if IOC_SIGNAL_RANGE_SUPPORT
extern OS_CONST_H iocDeviceHdr rookie_hdr;
#endif


/* IO device hardware version. */
#define ROOKIE_HW "carol"

/* Defines to check in code with #ifdef to know if signal is configured in JSON. */
#define ROOKIE_EXP_LEFT
#define ROOKIE_EXP_RIGHT
#define ROOKIE_EXP_FORWARD
#define ROOKIE_EXP_BACKWARD
#define ROOKIE_IMP_LEFTTURN
#define ROOKIE_IMP_RIGHTTURN
#define ROOKIE_IMP_STRAIGHTFORWARD
#define ROOKIE_IMP_FORWARDBACKWARD

#ifndef IOBOARD_DEVICE_NAME
#define IOBOARD_DEVICE_NAME "rookie"
#endif

OSAL_C_HEADER_ENDS
#endif
